version: '3.9'

services:

  frontend:
    build: ./frintend
    container_name: ecommerce-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frintend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
    networks:
      - mern-network

  mongo:
    image: mongo
    container_name: ecommerce-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

volumes:
  mongo-data:
  

networks:
  mern-network:
    driver: bridge